<a href="https://colab.research.google.com/github/Atul101-oss/Aryabhatta/blob/main/DSE_Practical_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('''
------------------------------------------------------------Name : Atul---------------------------------------------------------
																												Roll No.: CSC/22/11

Que:- Write programs in Python using NumPy library to do the following:

	a. Create a two dimensional array, ARR1 having random values from 0 to 1. Compute the mean, standard deviation,
		and variance of ARR1 along the second axis.

	b. Create a 2-dimensional array of size m x n integer elements, also print the shape,
		type and data type of the array and then reshape it into an n x m array,
		where n and m are user inputs given at the run time.

	c. Test whether the elements of a given 1D array are zero, non-zero and NaN.
		Record the indices of these elements in three separate arrays.

	d. Create three random arrays of the same size: Array1, Array2 and Array3.
		Subtract Array 2 from Array3 and store in Array4. Create another array Array5 having two times the values in Array1.
		Find Co-variance and Correlation of Array1 with Array4 and Array5 respectively.

	e. Create two random arrays of the same size 10: Array1, and Array2.
		Find the sum of the first half of both the arrays and product of the second half of both the arrays.

	f. Create an array with random values. Determine the size of the memory occupied by the array.

	g. Create a 2-dimensional array of size m x n having integer elements in the range (10,100).
		Write statements to swap any two rows, reverse a specified column and store updated array in another variable
--------------------------------------------------------------------------------------------------------------------------------
''')


------------------------------------------------------------Name : Atul---------------------------------------------------------
														Roll No.: CSC/22/11
      
Que:- Write programs in Python using NumPy library to do the following:

	a. Create a two dimensional array, ARR1 having random values from 0 to 1. Compute the mean, standard deviation,
		and variance of ARR1 along the second axis.

	b. Create a 2-dimensional array of size m x n integer elements, also print the shape,
		type and data type of the array and then reshape it into an n x m array,
		where n and m are user inputs given at the run time.

	c. Test whether the elements of a given 1D array are zero, non-zero and NaN.
		Record the indices of these elements in three separate arrays.

	d. Create three random arrays of the same size: Array1, Array2 and Array3.
		Subtract Array 2 from Array3 and store in Array4. Create another array Array5 having two times the values in Array1.
		Find Co-variance and Correlation of A

In [ ]:
import numpy as np


In [ ]:
#Create a two dimensional array, ARR1 having random values from 0 to 1. Compute the mean, standard deviation,and variance of ARR1 along the second axis

ARR1 = np.random.rand(4,5)

Mean = np.mean(ARR1)
STD = np.std(ARR1)
Var = np.var(ARR1)
print(f"{ARR1}\n\nMean = {Mean}\nSTD = {STD}\nVarience = {Var}")

[[0.6297375  0.11165099 0.75988232 0.91585086 0.24879637]
 [0.11431885 0.88832619 0.0156646  0.21623191 0.89141813]
 [0.23084661 0.35205997 0.23841293 0.16385306 0.2004409 ]
 [0.81769731 0.33572923 0.97699241 0.26937541 0.63618699]]

Mean = 0.4506736268945052
STD = 0.3148873012352259
Varience = 0.09915401247920388


In [ ]:
#Create a 2-dimensional array of size m x n integer elements, also print the shape,
#		type and data type of the array and then reshape it into an n x m array,
#		where n and m are user inputs given at the run time.

m = int(input("Enter rows : "))
n = int(input("Enter columns : "))

arr = np.random.randint(0,100, size=(m,n))
print(arr,"\n")
print("shape : ",arr.shape)
print("array type : ", arr.dtype)
arr.reshape(n,m)
print("shape after reshape : ",arr.shape)

Enter rows : 5
Enter columns : 7
shape :  (5, 7)
array type :  int64
shape after reshape :  [[35  5 10 84  1]
 [72 56 91 32 51]
 [73 54 55  9 11]
 [77 15 84 98 56]
 [93 12  1 32 89]
 [70 43  6 41 48]
 [67 45 54 25 44]]


In [ ]:
#   Test whether the elements of a given 1D array are zero, non-zero and NaN.
#		Record the indices of these elements in three separate arrays.

arr1d = np.array([1,0,3,5,np.nan,3,0,3,np.nan,7])
print(f"Example array !\n{arr1d}\n")

print("is any NaN value : ",np.isnan(arr1d).all())
print("is there any 0 in arr1d : ",(arr1d == 0).all())
print("is there any integer except 0 in arr1d : ",(arr1d != 0).all())

NaN_arr = [i for i in range(len(arr1d)) if np.isnan(arr1d)[i]]
zero_arr = [i for i in range(len(arr1d)) if (arr1d == 0)[i]]
any_int_arr = [i for i in range(len(arr1d)) if (arr1d !=0)[i]]

print(f"\nNaN_arr = {NaN_arr}\nzero_arr = {zero_arr}\nany_int_arr = {any_int_arr}")


Example array !
[ 1.  0.  3.  5. nan  3.  0.  3. nan  7.]

is any NaN value :  False
is there any 0 in arr1d :  False
is there any integer except 0 in arr1d :  False

NaN_arr = [4, 8]
zero_arr = [1, 6]
any_int_arr = [0, 2, 3, 4, 5, 7, 8, 9]


In [ ]:
#   Create three random arrays of the same size: Array1, Array2 and Array3.
#		Subtract Array 2 from Array3 and store in Array4. Create another array Array5 having two times the values in Array1.
#		Find Co-variance and Correlation of Array1 with Array4 and Array5 respectively.


array1 = np.random.randint(10, size=(8))
array2 = np.random.randint(10, size=(8))
array3 = np.random.randint(10, size=(8))

array4 = np.subtract(array3,array2)
array5 = 2*array1

print(f"Given ! \narray1 = {array1} \narray2 = {array2} \narray3 = {array3}")
print(f"\nAfter Mainipulation ! \narray4 = {array4} \narray5 = {array5}")

print(f"\nCo-Varience of array1 with array4 \n{np.cov(array1,array4)}")
print(f"\nCo-Relation of array1 with array5 \n{np.corrcoef(array1,array5)}")

Given ! 
array1 = [2 3 3 5 8 6 4 7] 
array2 = [8 3 9 4 1 8 7 2] 
array3 = [1 6 8 2 7 8 3 8]

After Mainipulation ! 
array4 = [-7  3 -1 -2  6  0 -4  6] 
array5 = [ 4  6  6 10 16 12  8 14]

Co-Varience of array1 with array4 
[[ 4.5         7.32142857]
 [ 7.32142857 21.55357143]]

Co-Relation of array1 with array5 
[[1. 1.]
 [1. 1.]]


In [ ]:
#   Create two random arrays of the same size 10: Array1, and Array2.
#   Find the sum of the first half of both the arrays and product of the second half of both the arrays.

Array1 = np.random.randint(100, size=(10))
Array2 = np.random.randint(100, size=(10))

sum1 = np.sum(Array1[: 5])
sum2 = np.sum(Array2[: 5])

product1 = np.prod(Array1[5 :])
product2 = np.prod(Array2[5 :])

print(f"Given ! \nArray1 = {Array1} \nArray2 = {Array2}")
print(f"\nSum ! \nArray1 = {sum1} \nArray2 = {sum2}")
print(f"\nProduct ! \nArray1 = {product1} \nArray2 = {product2}")

Given ! 
Array1 = [28 77 89 83 16 36 16 89 52 41] 
Array2 = [37 23 67 82  8 12 99 37 59 64]

Sum ! 
Array1 = 293 
Array2 = 217

Product ! 
Array1 = 109294848 
Array2 = 165977856


In [ ]:
#   Create an array with random values. Determine the size of the memory occupied by the array.

rand_array = np.random.rand(5)
memory = rand_array.size*rand_array.itemsize

print("Memory occupied by rand_array =>",memory,"bytes")

Memory occupied by rand_array => 40 bytes


In [ ]:
#   Create a 2-dimensional array of size m x n having integer elements in the range (10,100).
#		Write statements to swap any two rows, reverse a specified column and store updated array in another variable

array2d = np.random.randint(10,100, size=(5,9))
print(f"Before Mainipulation! \n{array2d}")

i = np.random.randint(5)
j = np.random.randint(5)
array2d[i], array2d[j] = array2d[j], array2d[i]

array2d[:, i] = array2d[::-1, i]

print(f"\nAfter Mainipulation! (i = {i}, j = {j}) \n{array2d}")




Before Mainipulation! 
[[71 57 76 19 51 32 67 20 99]
 [47 56 14 11 65 73 23 69 37]
 [17 77 30 25 21 64 82 63 34]
 [82 75 16 50 60 18 20 97 96]
 [84 49 98 63 65 90 88 81 83]]

After Mainipulation! (i = 1, j = 2) 
[[71 49 76 19 51 32 67 20 99]
 [17 75 30 25 21 64 82 63 34]
 [17 77 30 25 21 64 82 63 34]
 [82 77 16 50 60 18 20 97 96]
 [84 57 98 63 65 90 88 81 83]]
